# Generated by Django 4.2.5 on 2023-10-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id_member', models.AutoField(primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=20)),
                ('gen', models.CharField(max_length=2)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(max_length=2)),
                ('horoskop', models.CharField(max_length=40)),
                ('height', models.IntegerField()),
                ('is_capt', models.BooleanField(default=False)),
                ('is_gen', models.BooleanField(default=True)),
            ],
        ),
    ]
