# Generated by Django 4.2.5 on 2023-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkt48', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_gen',
        ),
        migrations.AddField(
            model_name='member',
            name='is_cent',
            field=models.BooleanField(default=False),
        ),
    ]
