# Generated by Django 4.2.5 on 2023-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkt48', '0002_remove_member_is_gen_member_is_cent'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, default="{% static 'img/logo.png' %}", null=True, upload_to=''),
        ),
    ]
