# Generated by Django 4.2.5 on 2023-10-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jkt48', '0003_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_trainee',
            field=models.BooleanField(default=False),
        ),
    ]
